# -*- coding: utf-8 -*-
"""bj2839.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oGMLtk8U3S2bpUBtloI89gY6DATH4d3c
"""

# 2839번 : 설탕 배달

n = int(input())
cnt = 0

while n >= 0:
    if n % 3 == 0 or n % 3 == 5:
        n -= 3
        cnt += 1
    elif n % 5 == 0:
        n -= 5
        cnt += 1
    else:
        cnt = -1
        break

print(cnt)