# -*- coding: utf-8 -*-
"""LV2.더 맵게

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CAWP5POY4GwRpiSq1tYXbyfZsQGFr6fh
"""

from heapq import *

def solution(scoville, K):
    answer = 0
    heapify(scoville)
    
    while scoville[0] < K and len(scoville) > 1:
        a = heappop(scoville)
        b = heappop(scoville)
        heappush(scoville, a + b*2)
        answer += 1
    
    return answer if scoville[0] >= K else -1

print(solution([1, 2, 3, 9, 10, 12], 7))