# -*- coding: utf-8 -*-
"""LV3.이중우선순위큐

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IqwR0mYXZVGxHvQr2KSIedHrkF355BfH
"""

import heapq

def solution(operations):
    heap = []
    for op in operations:
        print(op)
        command, num = op.split()
        if command == 'D':
            if not heap:  # 삭제할 데이터가 없다면
                continue
            if num == '1':  # 최댓값 삭제
                heap.remove(heapq.nlargest(1, heap)[0])
            else:  # 최솟값 삭제
                heapq.heappop(heap)
        else:
            heapq.heappush(heap, int(num))

    return [heapq.nlargest(1, heap)[0], heap[0]] if heap else [0, 0]

print(solution(["I 16", "I -5643", "D -1", "D 1", "D 1", "I 123", "D -1"]))
print(solution(["I -45", "I 653", "D 1", "I -642", "I 45", "I 97", "D 1", "D -1", "I 333"]))