# -*- coding: utf-8 -*-
"""LV1.모의고사

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17yaOYa3oQcvVqerZMW4woYn3-02LJVge
"""

def solution(answers):
    answer = []
    a1 = [1,2,3,4,5]
    a2 = [2,1,2,3,2,4,2,5]
    a3 = [3,3,1,1,2,2,4,4,5,5]
    cnt = [0, 0, 0]
    for i in range(len(answers)):
        if answers[i] == a1[i%5]:
            cnt[0] += 1
        if answers[i] == a2[i%8]:
            cnt[1] += 1
        if answers[i] == a3[i%10]:
            cnt[2] += 1
            
    maxx = max(cnt)

    for idx, i in enumerate(cnt):
        if i == maxx:
            answer.append(idx+1)
    return sorted(answer)

print(solution([1, 2, 3, 4, 5]))
print(solution([1, 3, 2, 4, 2]))