# -*- coding: utf-8 -*-
"""LV2.소수 찾기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EORbFZYPQPl6N_nt3_i5fG43-K5Ku9kF
"""

from itertools import permutations

def checkPrime(n):
    if n < 2:                                 
        return False
            
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    
    return True
                   
def solution(numbers):
    answer = []
    numbers = list(numbers)
    temp = []
    
    for i in range(1, len(numbers)+1):
        temp += list(permutations(numbers, i)) 
    num = [int(''.join(t)) for t in temp] 
    
    for i in num:
        if checkPrime(i):
            answer.append(i)
    
    return len(set(answer))

print(solution("17"))
print(solution("011"))