# -*- coding: utf-8 -*-
"""LV2.카펫

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WXSzo8WkU6lvFG_W2GfqiWkKykuW0uWG
"""

def solution(brown, yellow):
    answer = []
    total = brown + yellow                  # a * b = total
    for b in range(1,total+1):
        if (total / b) % 1 == 0:            # total / b = a
            a = total / b
            if a >= b:                      # a >= b
                if 2*a + 2*b == brown + 4:  # 2*a + 2*b = brown + 4 
                    return [int(a),b]
            
    return answer

print(solution(10, 2))
print(solution(8, 1))
print(solution(24, 24))