# -*- coding: utf-8 -*-
"""LV2.주식가격

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aIuzhJ2kBCIqS-Y-aQrZDv2mInVNBkvY
"""

def solution(prices):
    
    answer = [0 for _ in range(len(prices))]
    
    for i in range(len(prices)):
        for j in range(i+1, len(prices)):
            answer[i] += 1
            if prices[i] > prices[j]:
                break
        
    return answer

print(solution([1, 2, 3, 2, 3]))

# 위에 코드로도 효율성 테스트를 통과하지만 스택/큐를 사용하여 코드 작성

def solution(prices):
    answer = [len(prices)-i-1 for i in range(len(prices))]
    stack = [0]

    print(answer)

    for i in range(1, len(prices)):
        while stack:
            idx = stack[-1]
            print(idx)

            if prices[idx] > prices[i]:
                answer[idx] = i - idx
                stack.pop()
            else:
                break
        stack.append(i)

    return answer

print(solution([1, 2, 3, 2, 3]))