# -*- coding: utf-8 -*-
"""LV2.다리를 지나는 트럭

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R1BMi9Nli5SJ0PoE3zquwH9MiJD-km6X
"""

# 테스트 5에 대해서 시간 초과 발생

def solution(bridge_length, weight, truck_weights):
    answer = 0

    q = [0 for _ in range(bridge_length)]
    
    while q:
        answer += 1
        q.pop(0)
        if truck_weights:
            if sum(q) + truck_weights[0] <= weight:
                q.append(truck_weights.pop(0))
            else:
                q.append(0)

    return answer

print(solution(2, 10, [7,4,5,6]))
print(solution(100, 100, [10]))
print(solution(100, 100, [10,10,10,10,10,10,10,10,10,10]))

# 시간복잡도를 위해 deque 사용

from collections import deque

def solution(bridge_length, weight, truck_weights):
    answer = 0
    bridge_deque = deque([0] * bridge_length)
    truck_deque = deque(truck_weights)

    while bridge_deque:
        answer += 1
        bridge_deque.popleft()
        if truck_deque:
            if sum(bridge_deque) + truck_deque[0] <= weight:
                bridge_deque.append(truck_deque.popleft())
            else:
                bridge_deque.append(0)
                
    return answer

print(solution(2, 10, [7,4,5,6]))
print(solution(100, 100, [10]))
print(solution(100, 100, [10,10,10,10,10,10,10,10,10,10]))