# -*- coding: utf-8 -*-
"""LV2.전화번호 목록

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yK3Ev3OZpf3NFOyXZ-6329OZxoA6v6oH
"""

def solution(phone_book):
    answer = True

    phone_book.sort()

    for i in range(len(phone_book)-1):
        if phone_book[i] == phone_book[i+1][0:len(phone_book[i])]:
            answer = False
            break

    return answer