# -*- coding: utf-8 -*-
"""LV2.위장

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sdord83wceSKMjtm_hFIjyPLFVtrJpjP
"""

def solution(clothes):
    answer = 0
    multi = 1
    dic = {}

    b = []

    for i in clothes:
        n = i[0]
        t = i[1]
        dic[t] = 0

    for i in clothes:
        t = i[1]
        dic[t] += 1

    for i in dic.values():
        answer += i
        multi = (i+1)*multi

    if len(list(dic.keys())) > 1:
        return (multi - 1)

    else:
        return answer

print(solution([["yellow_hat", "headgear"], ["blue_sunglasses", "eyewear"], ["green_turban", "headgear"]]))
print(solution([["crow_mask", "face"], ["blue_sunglasses", "face"], ["smoky_makeup", "face"]]))