# -*- coding: utf-8 -*-
"""LV3_베스트엘범

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/188VX8C_6hOvYC1LfFsfo8vjnj3wMfCCg
"""

def solution(genres, plays):
    answer = []
    dic = {}
    total = [[genres[i], plays[i], i] for i in range(len(plays))]
    total.sort(key = lambda x : (x[0], -x[1], x[2]))

    for i in genres:
        dic[i] = 0

    for i, j in zip(genres, plays):
        dic[i] += j

    dic = sorted(dic.items(), key = lambda x : -x[1])

    for i in dic:
        cnt = 0
        for j in total:
            if i[0] == j[0]:
                if cnt <= 1:
                    answer.append(j[2])
                else:
                    break
                cnt += 1
    return answer

print(solution(["classic", "pop", "classic", "classic", "pop"], [500, 600, 150, 800, 2500]))