# -*- coding: utf-8 -*-
"""1545.거꾸로 출력해 보아요

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1asBxXcyztMjbL6uczKOqXeGk2V2R9Zxp
"""

n = int(input())

for i in range(n, -1, -1):
    print(i, end = ' ')