# -*- coding: utf-8 -*-
"""1933.간단한 N의 약수

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13iygdRKJ0Vtjf4sMkJLHTedlk41cdOqx
"""

n = int(input())
a = []

for i in range(1, n+1):
    if n % i == 0:
        a.append(str(i))

print(' '.join(a))