# -*- coding: utf-8 -*-
"""1936.1대1 가위바위보

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15tZ-4I-t3K4hXHkB33ZfPRhLspTliF_t
"""

a, b = map(int, input().split())

if a == 1 and b == 2:
    print("B")
elif a == 1 and b == 3:
    print("A")
elif a == 2 and b == 3:
    print("B")
elif b == 1 and a == 2:
    print("A")
elif b == 1 and a == 3:
    print("B")
else:
    print("A")

a, b = map(int, input().split())

if (a == (b + 1) % 3):
    print("B")
else:
    print("A")