# -*- coding: utf-8 -*-
"""1938.아주 간단한 계산기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ATFxNZ1aBBKunsux89O3jL6O58lgwo44
"""

a, b = map(int, input().split())

print(a+b)
print(a-b)
print(a*b)
print(a//b)