# -*- coding: utf-8 -*-
"""2019.더블더블

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pq3U94A9aMLzkksbDV1pylbOKwbjAitz
"""

n = int(input())

for i in range(n+1):
    print(2**i, end = ' ')