# -*- coding: utf-8 -*-
"""2025.N줄덧셈

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IzpJ_rXBJcdkcCVeQltdCdeAooP491o1
"""

n = int(input())
answer = 0

for i in range(1, n+1):
    answer += i

print(answer)