# -*- coding: utf-8 -*-
"""2027.대각선 출력하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QE4gyfoafjGfQCnlN00dgO9v-RXnIJej
"""

for i in range(5):
    for j in range(5):
        if i==j:
            print("#", end = '')
        else:
            print("+", end = '')
    print()