# -*- coding: utf-8 -*-
"""2043.서랍의 비밀번호

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ir6-K93U6BfD-TBlZ7-uIXPVZvWEYVl4
"""

p, k = map(int, input().split())
cnt = 1

while p != k:
    k += 1
    cnt += 1

print(cnt)