# -*- coding: utf-8 -*-
"""2046.스탬프 찍기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13__leYVhVjv5O7UxjbkuMICrmDTN9M2A
"""

n = int(input())

print("#"*n)