# -*- coding: utf-8 -*-
"""2047.신문 헤드라인

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mfqPoRH3HeEyyS0oCmkrXDHkPql8DRTC
"""

n = input()
answer = ''

for i in n:
    if i.islower():
        answer += i.upper()
    else:
        answer += i

print(answer)