# -*- coding: utf-8 -*-
"""2050.알파벳을 숫자로 변환

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FllxkeA4VIcijC8qZbS14OdDJDJ5-zPE
"""

n = input()

for i in n:
    print((ord(i)-64), end =' ')