# -*- coding: utf-8 -*-
"""2056.연월일 달력

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-hohblbA9iBSd5kI6ad3ZW3x_ip2TO4R
"""

n = int(input())

for i in range(1, n+1):
    a = input()
    year = a[0:4]
    month = a[4:6]
    day = a[6:8]
    answer = ''
    if int(year) >= 0:
        if int(month) > 0 and int(month) <= 12:
            if int(month) == 2 and int(day) > 0 and int(day) <=28:
                answer = "#"+ str(i) +" " + str(year) + "/" + str(month) + "/" + str(day)
            elif int(month) == 4 or int(month) == 6 or int(month) == 9 or int(month) == 11:
                if int(day) > 0 and int(day) <=30:
                    answer = "#"+ str(i) +" " + str(year) + "/" + str(month) + "/" + str(day)
            elif int(month) == 1 or int(month) == 3 or int(month) == 5 or int(month) == 7 or int(month) == 8 or int(month) == 10 or int(month) == 12:
                if int(day) > 0 and int(day) <=31:
                    answer = "#"+ str(i) +" " + str(year) + "/" + str(month) + "/" + str(day)
            else:
                answer += "#"+ str(i) +" " + "-1"
        else:
            answer += "#"+ str(i) +" " + "-1"
    else: 
        answer += "#"+ str(i) +" " + "-1"
    print(answer)