# -*- coding: utf-8 -*-
"""2058.자릿수 더하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QAHhNV-V_jjAG8sdoqDFM2sE9ii4gs-3
"""

n = int(input())
answer = 0

while n > 0:
    answer += n % 10
    n = n // 10

print(answer)