# -*- coding: utf-8 -*-
"""2063.중간값 찾기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x6NtQPTh3sSW4xiVloB2LNLiCEvwTQhF
"""

n = int(input())
a = list(map(int, input().split()))

a.sort()

print(a[n//2])