# -*- coding: utf-8 -*-
"""2070.큰 놈, 작은 놈, 같은 놈

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dvID2ccBjrpu_7gzZxQjGpWwTrwyRhns
"""

n = int(input())

for i in range(1, n+1):
    a ,b = map(int, input().split())
    if a > b:
        c = ">"
    elif a == b:
        c = "="
    else:
        c = "<"

    print("#"+str(i)+" "+c)