# -*- coding: utf-8 -*-
"""2071.평균값 구하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ZUkJTi--hrb4YA95gqyC-F_UgQ3MjoF
"""

n = int(input())

for i in range(1, n+1):
    a = list(map(int, input().split()))
    print(f'#{i} {round(sum(a)/10)}')