# -*- coding: utf-8 -*-
"""2072. 홀수만 더하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BbF4OAPAeYRoeJCGEvngQUFm4MwyRJiy
"""

n = int(input())

for i in range(1, n+1):
    result = 0
    arr = list(map(int, input().split()))
    for j in arr:
        if j % 2 == 1:
            result += j
    print(f"#{i} {result}")