# -*- coding: utf-8 -*-
"""12368.24시간

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rkllw6GwMAALGYWvGos4mKOXz5u5qYLW
"""

n = int(input())

for i in range(1, n+1):
    h1, h2 = map(int, input().split())
    h = h1 + h2
    if h >= 24:
        h = h %24
    print(f"#{i} {h}")