# -*- coding: utf-8 -*-
"""13218.조별과제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aSlaRRUIv7Ez5_rxMGFD8ST2cyWmteoT
"""

n = int(input())

for i in range(1, n+1):
    a = int(input())
    answer = a // 3
    print(f"#{i} {answer}")