# -*- coding: utf-8 -*-
"""3131.100만 이하의 모든 소수

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lalmaCfImiAQF_VaS-5FXb-WN8AzLs9z
"""

N = 1000000
arr= [True]*(N+1)

for i in range(2,int(N**0.5)+1):
    if arr[i]:
        for j in range(i*2,N+1,i):
            arr[j] = False
for i in range(2,len(arr)):
    if arr[i]:
        print(i,end = " ")