# -*- coding: utf-8 -*-
"""5603.[Professional]건초더미

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vub43v1qgKXO1LXK64ldsp9_SAOUbnyG
"""

t = int(input())

for i in range(1, t+1):
    cnt = 0
    n = int(input())
    arr = [int(input()) for _ in range(n)]
    aver = sum(arr) // len(arr)
    for j in arr:
        if j > aver:
            cnt += j - aver

    print(f'#{i} {cnt}')