# -*- coding: utf-8 -*-
"""32.3진법 뒤집기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZP_lVeA4jw9H3eR7hRVaxwWnxxxFac01
"""

def solution(n):
    result = ''
    while n:
        result += str(n%3)
        n = n//3
    return int(result, 3)

print(solution(45))
print(solution(125))