# -*- coding: utf-8 -*-
"""9.정수 내림차순으로 배치하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q1qSEMddLRCRoz2PnvOujKMLA9Rj8DJq
"""

def solution(n):
    answer = []

    while n > 0:
        answer.append(n%10)
        n = n // 10

    answer.sort(reverse = True)
    return int(''.join(map(str, answer)))

print(solution(118372))