# -*- coding: utf-8 -*-
"""20.수박수박수박수?

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GVZ-IXfsfSTbA6yB5RV2jqyR9xQpFnbi
"""

def solution(n):
    answer = ''
    for i in range(n):
        if i % 2 == 0:
            answer += "수"
        else:
            answer += "박"
    return answer