# -*- coding: utf-8 -*-
"""34.시저 암호

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oppl1MqKADVs24Fko-XKnz40dTcLCNV1
"""

def solution(s, n):
    answer = ''
    
    for i in s:
        if i.islower():
            if ord(i)+n > 122:
                answer += chr(ord(i)+n-26).lower()
            else: 
                answer += chr(ord(i)+n).lower()
        elif i.isupper():
            if ord(i)+n > 90:
                answer += chr(ord(i)+n-26).upper()
            else:
                answer += chr(ord(i)+n).upper()
        else:
            answer += ' '
    return answer

print(solution("AB", 1))
print(solution("z", 1))
print(solution("a B z", 4))