# -*- coding: utf-8 -*-
"""2.나머지가 1이 되는 수 찾기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IKP_Xg-f1aCW1QvkG1LsnCk_7Rn5auX1
"""

def solution(n):
    answer = 0
    for i in range(n, 1, -1):
        if n % i == 1:
            answer = i
    return answer