# -*- coding: utf-8 -*-
"""23.문자열 내림차순으로 배치하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tSIQuhYor4oGldxMQtQEF_-b8nKc6U1D
"""

def solution(s):
    answer = ''

    low = []

    for i in s:
        low.append(ord(i))

    low.sort(reverse=True)

    for i in low:
        answer += chr(i)

    return answer

print(solution("Zbcdefg"))