# -*- coding: utf-8 -*-
"""16.핸드폰 번호 가리기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZSH6w7i_VgOuBpqZXPCn23vOqOtVz9kJ
"""

def solution(phone_number):
        return "*"*(len(phone_number)-4) + phone_number[-4:]

print(solution("01033334444"))
print(solution("027778888"))