# -*- coding: utf-8 -*-
"""7.자연수 뒤집어 배열로 만들기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PeWSzAxmoMaxXsVp-hLcAjLNSdi_jct7
"""

def solution(n):
    answer = []

    while n > 0:
        answer.append(n%10)
        n = n//10

    return answer

print(solution(12345))