# -*- coding: utf-8 -*-
"""3.짝수와 홀수

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YO5eSbVz4c739W6b971J7rzHURMkuE9U
"""

def solution(n):
    if n % 2 == 1:
        answer = "Odd"
    else:
        answer = "Even"
    
    return answer

print(solution(4))