# -*- coding: utf-8 -*-
"""10.문자열 내 p와 y의 개수

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZdIlSrbkCV3TeX3nOlBF6xTmilAbK3OC
"""

def solution(s):
    answer = True
    a = list(str(s))

    if sum([1 if i.lower() == "p" else 0 for i in a ]) != sum([1 if i.lower() == "y" else 0 for i in a ]):
        answer = False
    
    return answer

print(solution("PyY"))