# -*- coding: utf-8 -*-
"""39.숫자 문자열과 영단어

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ixnGyzYgX1wajhtfLZ42-aETCEtVdAiy
"""

def solution(n):
    a = {'zero':0, 'one':1, 'two':2, 'three':3, 'four':4, 'five':5, 'six':6, 'seven':7, 'eight':8, 'nine':9}
    
    for i in a.items():
        n = n.replace(i[0], str(i[1]))
    return int(n)

print(solution("one4seveneight"))
print(solution("23four5six7"))
print(solution("2three45sixseven"))
print(solution("123"))