# -*- coding: utf-8 -*-
"""13.콜라츠 추측

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cTUb0t7hp1EmPpW5nMRuU0_kfXYDhNTl
"""

def solution(num):
    answer = 0

    if num == 1:
        answer = 0

    while num != 1:
        if answer == 500:
            answer = -1
            break
        else:
            if num % 2 == 0:
                num /= 2
            else:
                num = num*3 + 1
        answer += 1
    return answer

print(solution(6))
print(solution(16))
print(solution(626331))