# -*- coding: utf-8 -*-
"""40.두 개 뽑아서 더하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kN5WbUggc5cAStz6iLipQf88ftCqO_AB
"""

def solution(numbers):
    answer = []

    for i in range(0, len(numbers)-1):
        for j in range(i+1, len(numbers)):
            answer.append(numbers[i]+numbers[j])
    answer = sorted(list(set(answer)))
    return answer

print(solution([2,1,3,4,1]))
print(solution([5,0,2,7]))