# -*- coding: utf-8 -*-
"""12.x만큼 간격이 있는 n개의 숫자

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13a6_r2ZA5u_3LAwCfPU5QaNHbs6TAdd0
"""

def solution(x, n):
    answer = []

    for i in range(1, n+1):
        answer.append(x*i)

    return answer

print(solution(2, 5))