# -*- coding: utf-8 -*-
"""8.평균 구하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WMXzeYFd6fRC0fQSypd_rM3l3oa2cqxg
"""

def solution(arr):
    
    return sum(arr)/len(arr)

print(solution([1,2,3,4]))