# -*- coding: utf-8 -*-
"""11.문자열을 정수로 바꾸기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dO5DZzYCyRT4jGzbv5gyjS2JiyqtiBjk
"""

def solution(s):
    answer = 0

    answer = int(s)

    return answer

print(solution("-1234"))