# -*- coding: utf-8 -*-
"""35.[1차] 비밀지도

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sTeJrqevh-7k2Xjk2BXxMsh9OweOv9F1
"""

def solution(n, arr1, arr2):
    answer = []

    for i in range(n):
        temp = bin(arr1[i])[2:]
        answer.append(temp.zfill(n))
    
    for i in range(n):
        temp1 = bin(arr2[i])[2:]
        answer.append(temp1.zfill(n))

    aa = []

    for i in range(n):
        a = ""
        for j, k in zip(answer[i], answer[i+n]):
            if j == '0' and k == '0':
                a += " "
            else:
                a += "#"
        aa.append(a)
    
    return aa

print(solution(5, [9, 20, 28, 18, 11], [30, 1, 21, 17, 28]))
print(solution(6, [46, 33, 33, 22, 31, 50], [27, 56, 19, 14, 14, 10]))