# -*- coding: utf-8 -*-
"""25.약수의 개수와 덧셈

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AJEgZQP66DKjIaUWFdvvu0kHrqnX-xSZ
"""

def solution(left, right):
    answer = 0
    
    for i in range(left, right+1):
        cnt = 0
        for j in range(1, i+1):
            if i % j == 0:
                cnt += 1

        if cnt % 2 == 0:
            answer += i
        else:
            answer -= i

    return answer

print(solution(13, 17))
print(solution(24, 27))