# -*- coding: utf-8 -*-
"""24.문자열 다루기 기본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17dq90L_7ktIatXMBjBhnEG4Xp3zw0CSl
"""

def solution(s):
    answer = True
    
    if len(s) != 4 and len(s) != 6:
        answer = False

    for i in s:
        if i.isalpha():
            answer = False

    return answer

print(solution("a234"))
print(solution("1234"))