# -*- coding: utf-8 -*-
"""27.직사각형 별찍기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ifgL6Bog8AHYw1vGTmHUCfjt6qwOF3ry
"""

a, b = map(int, input().strip().split(' '))
c = ("*"*a+"\n")*b

print(c)