# -*- coding: utf-8 -*-
"""45.소수 만들기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F56WlzZibsjzraQRvgHTTzgs2RrWE2a5
"""

from itertools import combinations

def check(a, b, c):
    for i in range(2, int((a+b+c)**0.5)+1):
        if (a+b+c) % i == 0:
            return False
    return True

def solution(nums):
    answer = list(combinations(nums, 3))
    result = 0
    for i in answer:
        if check(i[0], i[1], i[2]):
            result += 1
    
    return result

print(solution([1,2,3,4]))
print(solution([1,2,7,6,4]))