# -*- coding: utf-8 -*-
"""19.음양 더하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16tUoReeiSkXVNYkNPpnuMmpOPp4Wew7b
"""

def solution(absolutes, signs):
    answer = 0

    for i, j in zip(absolutes, signs):
        if j:
            answer += i
        else:
            answer -= i

    return answer

print(solution([4, 7, 12], [True, False, True]))
print(solution([1, 2, 3], [False, False, True]))