# -*- coding: utf-8 -*-
"""4.자릿수 더하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jWQahC_RyHnODpZ6pOkY8iqTgzduxoYM
"""

def solution(n):
    answer = 0
    while n > 0:
        answer += n % 10
        n = n // 10
    return answer

print(solution(123))