# -*- coding: utf-8 -*-
"""26.행렬의 덧셈

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1COzsT44_Pg26-3A6YIx8T6PXHsAQoBN-
"""

def solution(arr1, arr2):

    for i in range(len(arr1)):
        for j in range(len(arr1[0])):
            arr1[i][j] += arr2[i][j]

    return arr1

print(solution([[1,2],[2,3]], [[3,4],[5,6]]))
print(solution([[1],[2]], [[3],[4]]))