# -*- coding: utf-8 -*-
"""22.없는 숫자 더하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P6VTb7B1_aMms9zIbGS3L51p36nWGHCy
"""

def solution(numbers):
    answer = 0

    for i in range(10):
        if i not in numbers:
            answer += i

    return answer

print(solution([1,2,3,4,6,7,8,0]))
print(solution([5,8,4,0,6,7,9]))