# -*- coding: utf-8 -*-
"""41.2016년

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10WZXryYDsGQLIxoNHf8mmrO_jjtYcc3j
"""

def solution(a, b):
    answer = 0 
    day = ['FRI', 'SAT', 'SUN', 'MON', 'TUE', 'WED', 'THU']
    month = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

    for i in range(a-1):
        answer += month[i]
    
    answer += b-1

    return day[answer  % 7]

print(solution(5, 24))