# -*- coding: utf-8 -*-
"""6.약수의 합

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IxWmy7NZndOb3MrX_LLMxcSmeka8EclQ
"""

def solution(n):
    answer = 0

    for i in range(1, n+1):
        if n % i == 0:
            answer += i
    return answer

print(solution(5))