# -*- coding: utf-8 -*-
"""17.제일 작은 수 제거하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gtyOEW7GJ4hrjYdx8Ni_xpFeOSy9Z_Zt
"""

def solution(arr):
    answer = []

    if len(arr) > 2:
        arr.pop(arr.index(min(arr)))
        return arr
    else:
        return [-1]


print(solution([4,3,2,1]))
print(solution([10]))