# -*- coding: utf-8 -*-
"""1.성격 유형 검사하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eMeMFmxIhhja4QZU1N3P2e6m8LlR91Rt
"""

def solution(survey, choices):
    answer = ''
    result = {"R" : 0, "T" : 0, "C" : 0, "F" : 0, "J" : 0, "M" : 0, "A" : 0, "N" : 0}
    cnt = 0
    r_name =''
    for i in range(len(survey)):
        a = survey[i][0]
        b = survey[i][1]
        if choices[i] <= 4:
            result[a] += 4 - choices[i]
        else:
            result[b] += choices[i] - 4
    
    for j in result.keys():
        if cnt % 2 == 0:
            l_temp = result.get(j)
            l_name = j
        else:
            r_temp = result.get(j)
            r_name = j
        cnt += 1
        if cnt >= 2 and cnt % 2 == 0:
            if l_temp >= r_temp:
                answer += l_name
            else:
                answer += r_name
        
    return answer

survey = ["AN", "CF", "MJ", "RT", "NA"]
choices = [5, 3, 2, 7, 5]

print(solution(survey, choices))