# -*- coding: utf-8 -*-
"""43.소수 찾기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/160EqyWOhtiu6tjV9HwC9fusBPwS_Rpg7
"""

def solution(n):
    answer = 0

    for i in range(2, n+1):
        flag = True
        for j in range(2, i):
            if i % j == 0:
                flag = False
        if flag == True:
            answer += 1
    return answer

print(solution(10))
print(solution(5))

def solution(n):
    num = set(range(2,n+1))
    
    for i in range(2,n+1):
        if i in num:
            num -= set(range(2*i, n+1, i))
 
    return len(num)
    
print(solution(10))
print(solution(5))