# -*- coding: utf-8 -*-
"""37.문자열 내 마음대로 정렬하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PCJEAb3ACsiN7_rxrizZBMnVjBVfnz5k
"""

def solution(strings, n):
    return sorted(strings, key = lambda x : (x[n], x))

print(solution(["sun", "bed", "car"], 1))
print(solution(["abce", "abcd", "cdx"], 2))