# -*- coding: utf-8 -*-
"""28.부족한 금액 계산하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s4RzzO-m7BGWgElY_qEzGS8QVV39oCjc
"""

def solution(price, money, count):
    answer = 0
    total_price = 0

    while count != 0:
        total_price += count * price
        count -= 1

    if total_price > money:
        answer = total_price - money

    return answer

print(solution(3, 20, 4))