# -*- coding: utf-8 -*-
"""18.나누어 떨어지는 숫자 배열

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mRubkVVZx_FSUvXKBj6VMzJlwQYSOxUC
"""

def solution(arr, divisor):
    answer = []
    for i in arr:
        if i % divisor == 0:
            answer.append(i)
    answer.sort()
    if len(answer) == 0:
        answer.append(-1)
    return answer

print(solution([5, 9, 7, 10], 5))
print(solution([2, 36, 1, 3], 1))
print(solution([3, 2, 5], 10))