# -*- coding: utf-8 -*-
"""5.정수 제곱근 판별

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_3JzGFOB0ILrjZMkiBliL-PdfcoHydJ9
"""

def solution(n):
    answer = 0
    tmp = n ** (1/2)

    if tmp % 1 != 0:
        answer = -1

    else:
        answer = (tmp+1)**2
    
    return int(answer)

print(solution(121))