# -*- coding: utf-8 -*-
"""31.이상한 문자 만들기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y-jvBRwYvSvQcsT0HRITzcx-ublDx-lv
"""

def solution(s):
    answer = ''
    a = list(s.split(" "))

    for i in range(len(a)):
        for j in range(len(a[i])):
            if j % 2 == 0:
                answer += a[i][j].upper()
            else:
                answer += a[i][j].lower()
        if i != len(a)-1:
            answer += " "

    return answer

print(solution("try hello world"))