# -*- coding: utf-8 -*-
"""15.서울에서 김서방 찾기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GTH0CJ_OAZOFHkUJ2Y1Jk2a1iQRaTRGp
"""

def solution(seoul):

    for idx, i in enumerate(seoul):
        if i == "Kim":
            return(f'김서방은 {idx}에 있다')

print(solution(["Jane", "Kim"]))