# -*- coding: utf-8 -*-
"""54.삼총사

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bEapa61sbZ-0uaJ8pdBz_dXzHRqOFFid
"""

import itertools

def solution(n):
    answer = 0

    arr = list(itertools.combinations(n, 3))
    
    for i in arr:
        if sum(i) == 0:
            answer += 1

    return answer

print(solution([-2, 3, 0, 2, -5]))
print(solution([-3, -2, -1, 0, 1, 2, 3]))
print(solution([-1, 1, -1, 1]))