# -*- coding: utf-8 -*-
"""49.LV2_최솟값 만들기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zjV6OJk_KWmB2icLBSxebw7EsOzmcDIx
"""

def solution(A,B):
    answer = 0

    A.sort()
    B.sort(reverse = True)

    for i, j in zip(A, B):
        answer += i*j

    return answer

print(solution([1,4,2], [5,4,4]))
print(solution([1,2], [3, 4]))