# -*- coding: utf-8 -*-
"""47.LV2_최댓값과 최솟값

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sf04m_ZUOLaJPNkOsJ_Fv-cL20Wk2juN
"""

def solution(s):
    
    li = list(map(int, s.split()))
    return str(min(li)) + " " + str(max(li))

print(solution("1 2 3 4"))
print(solution("-1 -2 -3 -4"))
print(solution("-1 -1"))