# -*- coding: utf-8 -*-
"""53.LV2_피보나치 수

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13MlmlSzGKEH-QeUhbY3OuTbuhuclvFau
"""

def solution(n):
    answer = [0,1]
    for i in range(2, n+1):
        answer.append((answer[i-1]+answer[i-2]) % 1234567)

    return answer[-1]

print(solution(3))
print(solution(5))