# -*- coding: utf-8 -*-
"""50.LV2_이진 변환 반복하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jGslTB8vJlwrdpZMpi5PITjWVKQnOsuc
"""

def solution(s):
    answer = list(str(s))
    z_cnt = 0
    o_cnt = 0
    arr = []
    cnt = 0
    if len(answer) > 1:
        for i in answer:
            if i == '0':
                z_cnt += 1
            else:
                o_cnt += 1
        cnt += 1
                
        while True:
            b = bin(o_cnt)
            if len(b[2:]) == 1:
                break
            o_cnt = 0
            for i in b[2:]:
                if i == '0':
                    z_cnt += 1
                else:
                    o_cnt += 1
            cnt += 1
    else:
        return [0, 0]
        
    return [cnt, z_cnt]

print(solution("110010101001"))
print(solution("01110"))
print(solution("1111111"))