# -*- coding: utf-8 -*-
"""51.LV2_올바른 괄호

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rHkfpOHxvtJhoiWmeLnlzepFmH4ARN6S
"""

def solution(s):
    stack = []

    for i in s:
        if i == "(":
            stack.append(i)
        else:
            if stack == []:
                return False
            else:
                stack.pop()

    return stack==[]

print(solution("()()"))
print(solution("(())()"))
print(solution(")()("))
print(solution("(()("))