# -*- coding: utf-8 -*-
"""1284. 수도 요금 경쟁

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xO3w9tns4pRYQU0Xs61Ue2s5Mrw-Re8D
"""

n = int(input())

for i in range(1, n+1):
    p, q, r, s, w = map(int, input().split())

    if r >= w:
        if p*w >= q:
            print(f'#{i} {q}')
        else:
            print(f'#{i} {p*w}')
    else:
        if p*w >= q + s*(w-r):
            print(f'#{i} {q+s*(w-r)}')
        else:
            print(f'#{i} {p*w}')