# -*- coding: utf-8 -*-
"""1285.아름이의 돌 던지기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JP7tNYwHyF2Rifvhsw1UAr_IjJ3e0mTI
"""

t = int(input())
for i in range(1, t+1):
    n = int(input())
    answer = 0
    arr = list(map(int, input().split()))
    for j in range(len(arr)):
        arr[j] = abs(arr[j])
    arr.sort()
    result = arr[0]
    answer = arr.count(result)

    print(f'#{i} {result} {answer}')