# -*- coding: utf-8 -*-
"""1928.Base64 Decoder

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nmuBGOxTPBo90Ro_6R5DuNRCG0QZQ-ld
"""

n = int(input())
decode = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z',
      'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z',
      '0','1','2','3','4','5','6','7','8','9','+','/']
for i in range(1, n+1):
    a = list(input())
    answer = ''

    for j in range(len(a)):
        num = decode.index(a[j])
        incode = str(bin(num)[2:])
        while len(incode) < 6:
            incode = '0' + incode
        answer += incode
    
    b = ''
    for k in range(len(a)*6//8):
        c = int(answer[k*8:k*8+8], 2)
        b += chr(c)
    print(f'#{i} {b}')

from base64 import b64decode
 
T = int(input())
 
for tc in range(1, T + 1):
 
    word = input()
    res = b64decode(word).decode('UTF-8')
 
    print('#{} {}'.format(tc,res))