# -*- coding: utf-8 -*-
"""1940.가랏! RC카!

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hin1g-_4fK4Wl-baRYOzu0Hb2ltcey9y
"""

n = int(input())

for i in range(1, n+1):
    a = int(input())
    answer = 0
    gasok = 0
    for j in range(a):
        command = list(map(int, input().split()))
        if command[0] == 1:
            gasok += command[1]

        elif command[0] == 2:
            if gasok >= command[1]:
                gasok -= command[1]
            else:
                gasok = 0

        answer += gasok

    print(f"#{i} {answer}")