# -*- coding: utf-8 -*-
"""1945.간단한 소인수분해

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1913H0v-ELkPBCUEtMHSY-9qO2XmauzFs
"""

n = int(input())

for i in range(1,n+1):
    num = int(input())
    two = 0
    three = 0
    five = 0
    seven = 0
    eleven = 0
    while num > 0:
        if num % 2 == 0:
            two += 1
            num = num // 2
        elif num % 3 == 0:
            three += 1
            num = num // 3
        elif num % 5 == 0:
            five += 1
            num = num // 5
        elif num % 7 == 0:
            seven += 1
            num = num // 7
        elif num % 11 == 0:
            eleven += 1
            num = num // 11
        else:
            break
    print(f'#{i} {two} {three} {five} {seven} {eleven}')