# -*- coding: utf-8 -*-
"""1948.날짜 계산기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uqcHp-ISdjVGm-g-FZpjkvVQcCOOuSQz
"""

n = int(input())
day = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

for i in range(1, n+1):
    arr = list(map(int, input().split()))
    answer = 0
    if arr[0] == arr[2]:
        answer = arr[3] - arr[1] + 1
    else:
        for j in range(arr[0], arr[2]-1):
            answer += day[j]
        answer += day[arr[0]-1] - arr[1] +arr[3] + 1

    print(f"#{i} {answer}")