# -*- coding: utf-8 -*-
"""1979.어디에 단어가 들어갈 수 있을까

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AKhcSr9MLAU7RlYA8q_jZMsitmq3sXXk
"""

n = int(input())

for i in range(1, n+1):
    a = input()
    flag = True
    for j in range(len(a)//2):
        if a[j] != a[len(a)-j-1]:
            flag = False

    if flag == True:
        print(f"#{i} 1")
    else:
        print(f"#{i} 0")