# -*- coding: utf-8 -*-
"""1986.지그재그 숫자

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16hvydIXP44E0ql-J7V4tf8sZCVlLjQo6
"""

n = int(input())

for i in range(1, n+1):
    a = int(input())
    if a % 2 == 0:
        print(f'#{i} -{(a // 2)}')
    else:
        print(f'#{i} {(a+1) // 2 }')