# -*- coding: utf-8 -*-
"""1989.초심자의 회문 검사

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WudpKCOEHX2NZVQ2S1Uvd0RDgpUWoLuJ
"""

n = int(input())

for i in range(1, n+1):
    a = input()
    flag = True
    for j in range(len(a)//2):
        if a[j] != a[len(a)-j-1]:
            flag = False

    if flag == True:
        print(f"#{i} 1")
    else:
        print(f"#{i} 0")