# -*- coding: utf-8 -*-
"""2007.패턴 마디의 길이

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X4vvy8q1MP1d4DA6CpCe3eZB---EXdJo
"""

case_count = int(input())

for i in range(1, case_count + 1):
    string = input()
    word = ''
    for char in string:
        word += char
        length = len(word)
        if word == string[length:length+length]:
            break
    print('#{} {}'.format(i, len(word)))