# -*- coding: utf-8 -*-
"""LV1.체육복

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CZGP9pVF3UXIu6xiANbzpp7Rg6W0W9If
"""

def solution(n, lost, reserve):
    
    arr = [1 for _ in range(n+1)]

    for i in range(len(lost)):
        arr[lost[i]] = 0

    for i in range(len(reserve)):
        if arr[reserve[i]] == 0:
            arr[reserve[i]] = 1
        else:
            arr[reserve[i]] = 2

    for i in range(1, len(arr)-1):
        if arr[i] == 0 and arr[i-1] == 2:
            arr[i] = 1; arr[i-1] = 1
        elif arr[i] == 0 and arr[i+1] == 2:
            arr[i] = 1; arr[i+1] = 1

    return arr.count(1)+arr.count(2)-1

print(solution(5, [2, 4], [1, 3, 5]))
print(solution(5, [2, 4], [3]))
print(solution(3, [3], [1]))