# -*- coding: utf-8 -*-
"""백준 브론즈5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EgxlW6EmRCcurAR4I5MB2qv6YG28PiJY
"""

a, b = map(int, input().split())
print(a+b)

a, b = map(int, input().split())
print(a-b)

n, m = map(int, input().split())
print(n//m)
print(n % m)

a = input()

print(int(a, 16))

a = int(input())
b = int(input())
print(a+b)

a,b = map(int, input().split())
a1, a2, a3, a4, a5 = map(int, input().split())

c = a*b
print(a1-c, a2-c, a3-c, a4-c, a5-c)

import math

a, b = map(int, input().split())
b = b - 0.99
print(math.ceil(a*b))

a, b, c, d, e, f = map(int, input().split())

if a > 1 or a < 1:
    print(1-a, end = ' ')
else:
    print(0, end = ' ')

if b > 1 or b < 1:
    print(1-b, end = ' ')
else:
    print(0, end = ' ')

if c > 2 or c < 2:
    print(2-c, end = ' ')
else:
    print(0, end = ' ')

if d > 2 or d < 2:
    print(2-d, end = ' ')
else:
    print(0, end = ' ')

if e > 2 or e < 2:
    print(2-e, end = ' ')
else:
    print(0, end = ' ')

if f > 8 or f < 8:
    print(8-f, end = ' ')
else:
    print(0)

arr=list(map(int,input().strip().split()))
arr2=[1,1,2,2,2,8]
print(" ".join(str(b-a) for a,b in zip(arr,arr2)))

a, b = map(int, input().split())
print(b*2 - a)

print(".  .   .")
print("|  | _ | _. _ ._ _  _")
print("|/\\|(/.|(_.(_)[ | )(/.")

print("       _.-;;-._")
print("'-..-'|   ||   |")
print("'-..-'|_.-;;-._|")
print("'-..-'|   ||   |")
print("'-..-'|_.-''-._|")

print("     /~\\")
print("    ( oo|")
print("    _\\=/_")
print("   /  _  \\")
print("  //|/.\\|\\\\")
print(" ||  \\ /  ||")
print("============")
print("|          |")
print("|          |")
print("|          |")

sum = 0

for i in range(5):
    b = int(input())
    sum += b

print(sum)

a = int(input())
b = int(input())
c = int(input())
d = int(input())
e = a+b+c+d

if e >= 60 or e < 3600:
    print(e//60)
    print(e%60)

a = int(input())
b = int(input())

print(2*b-a)

print("85")
print("wogus0")

a1, a2, b1, b2 = map(int, input().split())
print(a1*a2 + b1*b2)

a = int(input())

for i in range(1, a):
    a += i

print(a)

a = int(input())
b = int(input())

print((a+b)//2)
print((a-b)//2)

print("    8888888888  888    88888")
print("   88     88   88 88   88  88")
print("    8888  88  88   88  88888")
print("       88 88 888888888 88   88")
print("88888888  88 88     88 88    888888")
print("")
print("88  88  88   888    88888    888888")
print("88  88  88  88 88   88  88  88")
print("88 8888 88 88   88  88888    8888")
print(" 888  888 888888888 88  88      88")
print("  88  88  88     88 88   88888888")

print("SHIP NAME      CLASS          DEPLOYMENT IN SERVICE")
print("N2 Bomber      Heavy Fighter  Limited    21        ")
print("J-Type 327     Light Combat   Unlimited  1         ")
print("NX Cruiser     Medium Fighter Limited    18        ")
print("N1 Starfighter Medium Fighter Unlimited  25        ")
print("Royal Cruiser  Light Combat   Limited    4         ")

print("NFC West       W   L  T")
print("-----------------------")
print("Seattle        13  3  0")
print("San Francisco  12  4  0")
print("Arizona        10  6  0")
print("St. Louis      7   9  0")
print("")
print("NFC North      W   L  T")
print("-----------------------")
print("Green Bay      8   7  1")
print("Chicago        8   8  0")
print("Detroit        7   9  0")
print("Minnesota      5  10  1")

import time

now = time.time()
print(now)

a = ord(input())
a = a-44031
print(a)

a, b, c = map(int, input().split())

print(a+b+c)

print("고려대학교")

a, b = map(int, input().split())

print(a*b)

a, b = map(int,input().split())

for i in range(a):
    c, d = map(int, input().split())
    b = b + c - d

print("비와이")

x, y, n = map(int, input().split())

print(n//y, n%y)

a = int(input())

print(a%20000303)

a = int(input())

cnt = 0

for i in range(a):
    for j in range(a):
        if i==j:
            continue
        else:
            cnt += 1
print(cnt)

a = int(input())

if a%5 == 0:
    print(a//5)
else:
    print(a//5+1)

print("I'm Sexy")

a ,b = map(int, input().split())

print(a+b)

a = int(input())

print(4*a)

print("파이팅!!")

a, b = map(int, input().split())

print((a+b)*(a-b))

import datetime

now = datetime.datetime.now()

print(now.year)
print(now.strftime('%m'))
print(now.strftime('%d'))

a = int(input())

print(a-1946)

a ,b = map(int, input().split())

print(b-a, b)

a1, a2, a3 = map(int, input().split())
c1, c2, c3 = map(int, input().split())

print(c1-a3, c2//a2, c3-a1)

a = input()
print('Avengers: Endgame')

a, b, c, d = map(int, input().split())

if a%b == 0:
    price = (a//b-1)*c*d
else:
    price = a//b*c*d

print(price)

a = int(input())

print(a-543)

a, b, c = map(float, input().split())
d = int((a+1)*(b+1)/(c+1)-1)
print(d)

a, b, c, d = map(int, input().split())

print(56*a + 24*b + 14*c + 6*d)

a = int(input())

print(int(a*0.78), int(a - a*0.2*0.22))

a, b, c, d, e, f = map(int, input().split())

price = a*5 + b*5 + c*5 + d*5 + e*5 + f*5

print(price)

a ,b = map(int, input().split())
n1 = int(input())
n2 = int(input())

print(n1*n2)