# -*- coding: utf-8 -*-
"""백준 브론즈4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JzKmnUHbPJ84uhSFCBkt4XsaY6wi92WQ
"""

d, h, w = map(int, input().split())

r = d / ((h ** 2 + w ** 2) ** 0.5)
print(int(h * r), int(w * r))

a ,b = map(int, input().split())

print(abs(a-b))

a, b, c = map(int, input().split())

sum = 0

if a == b and b == c:
    sum = 10000 + a * 1000

elif a == b or b == c or a == c:
    if a == b :
        sum = 1000 + a * 100
    elif b == c:
        sum = 1000 + b * 100
    else:
        sum = 1000 + c * 100

else:
    sum = max(a, b, c) * 100

print(sum)

a, b = map(int, input().split())
c = int(input())

if b + c >= 60:
    a += (b+c)//60
    b = (b+c)%60
    if a >= 24:
        a -= 24
else:
    b = b+c

print(a, b)

a, b, c = map(int, input().split())
d = int(input())

if c + d >= 60:
    b += (c+d)//60
    c = (c+d)%60
    if b >= 60:
        a += b//60
        b = b % 60
        if a >= 24:
            a %= 24

else:
    c += d

print(a, b, c)

a, b, c = map(int, input().split())

mx = max(a, b, c)
mn = min(a, b, c)

if a != mn and a != mx:
    oth = a
if b != mn and b != mx:
    oth = b
if c != mn and c != mx:
    oth = c

print(mn, oth, mx)

a, b, c = map(int, input().split())

d = []
d.append(a)
d.append(b)
d.append(c)

d = sorted(d)
for i in range(len(d)):
    print(d[i], end = ' ')

a = int(input())

def num(a):
    sum = 0
    for i in range(1, a+1):
        sum += 2 * i
    return sum

if a%2 == 0:
    a = a // 2 + 1
    result = a * a

else:
    a = a // 2 +1
    result =  num(a)



print(result)

s, m = map(int, input().split())

if  s+m < 0 or s-m < 0 or (s + m) % 2 != 0:
    print(-1)

else:
    a = (s + m) // 2
    b = s - a
    print(max(a, b), min(a, b))

l = int(input())
a = int(input())
b = int(input())
c = int(input())
d = int(input())

if a%c != 0:
    kor = a//c + 1
else:
    kor = a//c

if b%d != 0:
    mat = b//d + 1
else:
    mat = b//d

print(l - max(kor, mat))

a = int(input())
b = int(input())
c = int(input())
d = int(input())
e = int(input())

print(min(a,b,c) + min(d,e) - 50)

a1, a2, a3, a4, a5, a6 = map(int,input().split())
b1, b2, b3, b4, b5, b6 = map(int,input().split())
c1, c2, c3, c4, c5, c6 = map(int,input().split())


def num(a1, a2, a3, a4, a5, a6):
    if a5 - a2 < 0:
        hour = a4 - a1 - 1
        mi = a5 - a2 + 60
        if a6 - a3 < 0:
            mi -= 1
            sec = a6 - a3 + 60
        else:
            sec = a6 - a3

    else:
        hour = a4 - a1
        mi = a5 - a2
        if a6 - a3 < 0:
            if a5 - a2 == 0:
                hour -= 1
                mi += 59
                sec = a6 - a3 + 60
            else:
                mi -= 1
                sec = a6 - a3 + 60
        else:
            sec = a6 - a3
        
    return hour, mi, sec

a = num(a1, a2, a3, a4, a5, a6)
b = num(b1, b2, b3, b4, b5, b6)
c = num(c1, c2, c3, c4, c5, c6)

print(a[0], a[1], a[2])
print(b[0], b[1], b[2])
print(c[0], c[1], c[2])

a1, b1, c1, d1 = map(int, input().split())
a2, b2, c2, d2 = map(int, input().split())

mg = a1 + b1 + c1 + d1
man = a2 + b2 + c2 + d2

if mg >= man:
    print(mg)
else:
    print(man)

a = int(input())
a = int(str(a), 2) * 17
print(bin(a)[2:])

d, h, m = map(int, input().split())
cnt = 1
day = d - 11

if day == 0:
    if h - 11 > 0:
        hour = h - 11
        if m - 11 >= 0:
            min = m - 11
        else:
            hour = hour - 1
            min = m - 11 + 60

    elif h - 11 == 0:
        hour = h - 11
        if m - 11 >= 0:
            min = m - 11
        else:
            cnt = 0
    elif h - 11 < 0:   
        cnt = 0

elif day > 0:
    if h - 11 > 0:
        hour = h - 11
        if m - 11 >= 0:
            min = m - 11
        else:
            hour = hour - 1
            min = m - 11 + 60

    elif h - 11 == 0:
        hour = h - 11
        if m - 11 >= 0:
            min = m - 11
        else:
            day = day - 1
            hour = 23
            min = m - 11 + 60
    elif h - 11 < 0:   
        day = day - 1
        hour = h - 11 + 24
        if m - 11 >= 0:
            min = m - 11
        else:
            hour = hour - 1
            min = m - 11 + 60

elif day < 0:
    cnt = 0
                    
if cnt == 1:
    total = (1440 * day) + (60 * hour) + min
    print(total)
    
elif cnt == 0:
    print("-1")

limit = int(input())
speed = int(input())

sub = speed - limit

if sub >= 31:
    print("You are speeding and your fine is $500.")
elif sub >= 21:
    print("You are speeding and your fine is $270.")
elif sub <= 20 and sub >= 1:
    print("You are speeding and your fine is $100.")
else :
    print("Congratulations, you are within the speed limit!")

a = int(input())
b = int(input())
c = int(input())
d = int(input())

if a < b and b < c and c < d:
    print("Fish Rising")

elif a > b and b > c and c > d:
    print("Fish Diving")

elif a == b and b == c and c == d and d == a:
    print("Fish At Constant Depth")   

else:
    print("No Fish")

a = int(input())
b = int(input())

if a >= 3 and b <= 4:
    print("TroyMartian")

if a <= 6 and b >= 2:
    print("VladSaturnian")

if a <= 2 and b <= 3:
    print("GraemeMercurian")

a = int(input())
b = int(input())
c = int(input())

print("The 1-3-sum is", 91 + a + b * 3 + c)

a, b = map(int, input().split())

if a % 2 == 0 or b % 2 == 0:
    print("0")

else:
    if a > b:
        print(b)
    else:
        print(a)

high, goal, cm = map(int, input().split())
key = goal - high

if key % cm == 0:
    print(key//cm)
else:
    print(key//cm+1)

x, k = map(int, input().split())

if x * 1000 >= k * 7000:
    print(k * 7000)
elif x * 1000 >= k * 3500:
    print(k * 3500)
elif x * 1000 >= k * 1750:
    print(k * 1750)
else:
    print(0)

a, b, c = map(int, input().split())

if a*a + b*b == c*c or b*b + c*c == a*a or c*c + a*a == b*b:
    print(1)
elif a==b==c:
    print(2)
else:
    print(0)

a = int(input())
b = int(input())
c = int(input())
d = int(input())
e = int(input())

if a <= 40:
    a = 40
if b <= 40:
    b = 40
if c <= 40:
    c = 40    
if d <= 40:
    d = 40
if e <= 40:
    e = 40        

print((a+b+c+d+e)//5)

sum = 0

for i in range(5):
    score = int(input())
    if score <= 40:
        score = 40
    sum += score

print(sum//5)

a = int(input())
b = int(input())
c = int(input())

if a + b + c != 180:
    print("Error")

elif a == b == c == 60:
    print("Equilateral")

elif a != b and b != c and c != a:
    print("Scalene")

elif (a == b and b != c) or (a == c and a != b) or (b == c and b != a):
    print("Isosceles")

k, n, m = map(int, input().split())

need = m - k * n

if need < 0:
    print(need * -1)
else:
    print(0)

time = int(input())

if time // 300 >= 1:
    a = time // 300
    time = time - a * 300
    if time // 60 >= 1:
        b = time // 60
        time = time - b * 60
        if time // 10 >= 1:
            c = time // 10
            time = time - c * 10
            if time == 0:
                print(a, b, c)
            else:
                print(-1)
        else:
            c = 0
            if time == 0:
                print(a, b, c)
            else:
                print(-1)
    else:
        b = 0
        if time // 10 >= 1:
            c = time // 10
            time = time - c * 10
            if time == 0:
                print(a, b, c)
            else:
                print(-1)
        else:
            c = 0
            if time == 0:
                print(a, b, c)
            else:
                print(-1)

else:
    a = 0
    if time // 60 >= 1:
        b = time // 60
        time = time - b * 60
        if time // 10 >= 1:
            c = time // 10
            time = time - c * 10
            if time == 0:
                print(a, b, c)
            else:
                print(-1)
        else:
            c = 0
            if time == 0:
                print(a, b, c)
            else:
                print(-1)
    else:
        b = 0
        if time // 10 >= 1:
            c = time // 10
            time = time - c * 10
            if time == 0:
                print(a, b, c)
            else:
                print(-1)
        else:
            c = 0
            if time == 0:
                print(a, b, c)
            else:
                print(-1)

num = int(input())

for i in range(3):
    tmp = float(input())
    tmp = tmp * 0.8
    print("${:.2f}".format(tmp))

num = int(input())

a = float(input())
b = float(input())
c = float(input())

print("${:.2f}".format(a * 0.8))
print("${:.2f}".format(b * 0.8))
print("${:.2f}".format(c * 0.8))

for _ in range(int(input())):
    tmp = float(input())
    print("$%.2f" % round(tmp * 0.8, 2))

x_price = int(input())
y_price = int(input())
y_max = int(input())
y_addprice = int(input())
p = int(input())

x = p*x_price
if y_max >= p:
    y = y_price
else:
    y = y_price + (p - y_max) * y_addprice

if y >= x:
    print(x)
else:
    print(y)

month = int(input())
day = int(input())

if month > 2:
    print("After")
elif month == 1:
    print("Before")
elif month == 2:
    if day < 18:
        print("Before")
    elif day == 18:
        print("Special")
    else:
        print("After")

cnt = 0

num = int(input())

a = list(map(int, input().split()))

for i in range(len(a)):
    if num == a[i]:
        cnt += 1

print(cnt)

a = int(input())

print(chr(44031+a))

cnt = 0

num = int(input())

tea = list(map(int, input().split()))

for i in range(len(tea)):
    if num == tea[i]:
        cnt += 1

print(cnt)

x_a, x_b = map(int, input().split())
y_a, y_b = map(int, input().split())

print(min(x_a + y_b, x_b + y_a))

sum = 0
min = 10000
cnt = 0

a = []

for i in range(4):
    tmp = int(input())
    a.append(tmp)
    if min >= tmp:
        min = tmp
        cnt = i

del a[cnt]


b = []
min1 = 10000
cnt1 = 0

for i in range(2):
    tmp2 = int(input())
    b.append(tmp2)
    if min1 >= tmp2:
        min1 = tmp2
        cnt1 = i

del b[cnt1]

for i in a:
    sum += i

for i in b:
    sum += i

print(sum)

x, y, c = map(int, input().split())

if x % c != 0:
    width = x//c + 1
else:
    width = x//c

if y % c != 0:
    high = y//c + 1
else:
    high = y//c

print(width * high)

a, b, c = map(int, input().split())

if a == b or b == c or c == a:
    print("S")

elif a+b==c or a+c==b or b+c==a:
    print("S")

else:
    print("N")

a, b = map(int, input().split())

if a == b:
    c = a
elif a > b:
    c = a
else:
    c = b

print(c)

a, b = map(int, input().split())

lab = 1

while True:
    if (b-a)*lab >= b:
        break
    lab += 1

print(lab)

a, b, c, d = map(int, input().split())

print(abs((a+d)-(b+c)))

sik = input().split()
a = int(sik[0])
b = int(sik[2]) 
c = int(sik[4])
if a + b == c:
    print("YES")
else:
    print("NO")

a = [input() for _ in range(6)]
count = a.count("W")
if count >= 5:
    print(1)
elif count >= 3:
    print(2)
elif count >= 1:
    print(3)
else:
    print(-1)

gallen = 3.785411784
mile = 1.609344

a = float(input())

result = 100 / ((mile / gallen) * a)
print("%.6f" % result)

x1, y1, x2, y2 = map(int, input().split())
x3, y3, x4, y4 = map(int, input().split())

x_min = min(x1, x3)
x_max = max(x2, x4)
y_min = min(y1, y3)
y_max = max(y2, y4)

x = x_max - x_min
y = y_max - y_min

print(max(x, y) ** 2)

import math

n = int(input())

a = n * math.sqrt(3) * 0.5

print(a * n * 0.5)

a = int(input())
b = int(input())
c = int(input())
d = int(input())
e = int(input())

if a < 0:
    sum = abs(a) * c + d + b * e
elif a == 0:
    sum = b * e + d
else:
    sum = (b - a) * e

print(sum)

a = str(input())
b = str(input())

a = int(a, 2)
b = int(b, 2)
c = a * b
print(bin(c)[2:])

s, t, d = map(int, input().split())
a = d / (s*2) * t
print(int(a))

x = input()

print('FA')

i, r = map(int, input().split())

if i == r and (i and r) != 0:
    print("Even", i*2)
elif i > r:
    print("Odd", i*2)
elif r > i:
    print("Odd", r*2)
elif i == 0 and r == 0:
    print("Not a moose")