# -*- coding: utf-8 -*-
"""벡준 단계별 2단계

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ll31NOLfMb9zzziSUryOTYlJn6nLYPX-
"""

a, b = map(int, input().split())

if a > b:
    print(">")
elif a == b:
    print("==")
else:
    print("<")

a = int(input())

if(90 <= a <= 100):
    print('A')
elif(80 <= a < 90):
    print('B')
elif(70 <= a < 80):
    print('C')
elif(60 <= a < 70):
    print('D')
else:
    print('F')

a = int(input())
    
if((a%4 == 0)and(a%100 != 0 or a%400 == 0)):
    print("1")
else:
    print("0")

x = int(input())
y = int(input())

if(x>0):
    if(y>0):
        print("1")
    elif(y<0):
        print("4")
elif(x<0):
    if(y>0):
        print("2")
    elif(y<0):
        print("3")

h, m = map(int, input().split())

if(m<45):
    m += 15
    if(h==0):
        h = 23
    else:
        h -= 1
elif(m>=45):
    m -= 45

print(h, m, end=' ')