# -*- coding: utf-8 -*-
"""코드업 파이썬 기초 100문제

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tZjGf_CqvSXsJo0e31LYVG5RAn1o-uQh
"""

print("Hello")

print("Hello World")

print("Hello")
print("World")

print("'Hello'")

print('"Hello World"')

print('"!@#$%^&*()\'')

print('"C:\\Download\\\'hello\'.py"')

print("""print("Hello\\nWorld")""")

a = input()
print(a)

n = int(input())
print(n)

n = float(input())
print(n)

a = input()
b = input()
print(a)
print(b)

a = input()
b = input()
print(b)
print(a)

n = float(input())
print(n)
print(n)
print(n)

a, b = input().split()
print(a)
print(b)

a, b = input().split()
print(b + " " + a)

a = input()
print(a, a, a)

a, b = input().split(':')
print(a, b, sep = ':')

a, b, c = input().split('.')
print(c, b, a, sep = '-')

a, b = input().split('-')
print(a, b, sep = '')

a = input()
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

a = input()
print(a[0:2], a[2:4], a[4:6])

a, b, c = input().split(':')
print(b)

a, b = input().split()
c = a+b
print(c)

a, b = map(int, input().split())
print(a + b)

a = float(input())
b = float(input())
print(a+b)

a = int(input())
print('%x'%a)

a = int(input())
print('%X'%a)

a = input()
b = int(a, 16)
print('%o' %b)

a = ord(input())
print(a)

a = int(input())
print(-a)

a = int(input())
print(chr(a))

a = ord(input())
print(chr(a+1))

a, b = map(int,input().split())
print(a-b)

a, b = map(float, input().split())
print(a*b)

a, b = input().split()
print(a*int(b))

a = int(input())
b = input()
print(a * b)

a,b = input().split()
c = int(a)**int(b)
print(c)

a, b = input().split()
c = float(a)**float(b)
print(c)

a, b = map(int, input().split())
print(a//b)

a, b = map(int, input().split())
print(a%b)

a = float(input())
print(format(a, ".2f"))

a,b = map(float, input().split())
print(format(a/b, ".3f"))

a, b = map(int, input().split())
print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a%b)
print(format(a/b, ".2f"))

a, b, c = map(int, input().split())
d = a+b+c
e = (format(d/3, ".2f"))
print(d, e)

a = int(input())
print(a<<1)

a, b = map(int, input().split())
print(a<<b)

a, b = map(int, input().split())
print(bool(a<b))

a, b = map(int, input().split())
print(bool(a==b))

a, b = map(int, input().split())
print(bool(a<=b))

a, b = map(int, input().split())
print(bool(a!=b))

n = int(input())
print(bool(n))

a = bool(int(input()))
print(not a)

a, b = input().split()
print(bool(int(a)) and bool(int(b)))

a, b = input().split()
print(bool(int(a)) or bool(int(b)))

a,b = map(int, input().split())
a = bool(a)
b = bool(b)
print((a and(not b)) or ((not a) and b))

a, b = map(int, input().split())
a = bool(a)
b = bool(b)
print((a and b) or ((not a) and (not b)))

a, b = map(int, input().split())
a = bool(a)
b = bool(b)
print(not a and not b)

a = int(input())
print(~a)

a, b = map(int, input().split())
print(a&b)

a, b = map(int, input().split())
print(a|b)

a, b = map(int, input().split())
print(a^b)

a, b = map(int, input().split())
c = (a if (a>=b) else b)
print(c)

a, b, c = map(int, input().split())
d = ((b if a>b else a)if((b if a>b else a)<c) else c)
print(d)

a, b, c = map(int, input().split())
if a%2 == 0:
    print(a)
if b%2 == 0:
    print(b)
if c%2 == 0:
    print(c)

a, b, c = map(int, input().split())
if a%2 == 0:
    print("even")
else:
    print("odd")
if b%2 == 0:
    print("even")
else:
    print("odd")
if c%2 == 0:
    print("even")
else:
    print("odd")

a = int(input())
if a<0:
    if a%2==0:
        print('A')
    else:
        print('B')
else:
    if a%2==0:
        print('C')
    else:
        print('D')

a = int(input())
if a>=90:
    print('A')
elif a>=70:
    print('B')
elif a>=40:
    print('C')
else:
    print('D')

a = input()

if a == 'A':
    print("best!!!")
elif a == 'B':
    print("good!!")
elif a == 'C':
    print("run!")
elif a == 'D':
    print("slowly~")
else:
    print("what?")

a = int(input())

if a//3 == 1:
    print("spring")
elif a//3 == 2:
    print("summer")
elif a//3 == 3:
    print("fall")
else:
    print("winter")

a = 1
while a !=0:
    a = int(input())
    if a==0:
        break
    print(a)

a = int(input())

while a != 0:
    print(a)
    a -= 1

a = int(input())

while a != 0 :
    a -= 1
    print(a)

a = ord(input())
t = ord('a')
while a>=t:
    print(chr(t), end = ' ')
    t += 1

a = int(input())
b = 0
while a>=b:
    print(b)
    b += 1

a = int(input())
for i in range(a+1):
    print(i)

a = int(input())
s = 0
for i in range(1, a+1):
    if i % 2 == 0:
        s += i
print(s)

a = 'a'
while a != 'q':
    a = input()
    print(a)

a = int(input())
b = 0 
result = 0
while a > result:
    b += 1
    result += b

print(b)

a, b = map(int, input().split())

for i in range(1, a+1):
    for j in range(1, b+1):
        print(i, j)

a = int(input(), 16)
b = 15

for j in range(1, b+1):
    print('%X'%a, '*%X'%j, '=%X'%(a*j), sep='')

a = int(input())

for i in range(1, a+1):
    if (i%10 == 3) or (i%10 == 6) or (i%10 == 9):
        print("X", end=' ')
    else:
        print(i, end=' ')



a, b, c = map(int, input().split())
cnt = 0

for i in range(0, a):
    for j in range(0, b):
        for k in range(0, c):
            print(i, j, k)
            cnt += 1
print(cnt)

h, b, c, s = map(float, input().split())

a = ((h*b*c*s)/8/1024/1024)

print(format(a, ".1f"), end = ' ')
print("MB")

w, h, b = map(float, input().split())

a = (w*h*b/8/1024/1024)

print(format(a, ".2f"), end = ' ')
print("MB")

a = int(input())
b = 1
result = 0;
while  a>result:
    result += b
    b += 1
print(result)

a = int(input())

for i in range(1, a+1):
    if i%3 == 0:
        continue;
    print(i, end=' ')

a, b, c = map(int, input().split())
cnt = 1
result = a

while c != cnt:
    result += b
    cnt += 1

print(result)

a, b, c = map(int, input().split())
cnt = 1
result = a

while c != cnt:
    result *= b
    cnt += 1

print(result)

a, m, d, n = map(int, input().split())
cnt = 1

while n > cnt:
    result = a*m+d
    cnt += 1
    a = result

print(result)

a, b, c = map(int, input().split())
d = 1
while d%a !=0 or d%b !=0 or d%c !=0:
    d += 1
print(d)

n = int(input())
a = input().split()
for i in range(n):
    a[i] = int(a[i])

d = []
for i in range(24):
    d.append(0)

for i in range(n):
    d[a[i]] += 1

for i in range(1, 24):
    print(d[i], end=' ')

n = int(input())
a = list(map(int,input().split()))

for i in range(n-1, -1, -1):
    print(a[i], end=' ')

n = int(input())
a = list(map(int,input().split()))

print(min(a))

d = []
for i in range(20):
    d.append([])
    for j in range(20):
        d[i].append(0)

n = int(input())
for i in range(n):
    x, y = input().split()
    d[int(x)][int(y)] = 1

for i in range(1,20):
    for j in range(1,20):
        print(d[i][j], end=' ')
    print()

d=[]
for i in range(20) :
  d.append([])
  for j in range(20) : 
    d[i].append(0)

for i in range(19) :
  a = input().split()
  for j in range(19) :
    d[i+1][j+1] = int(a[j])

n = int(input())
for i in range(n) :
  x,y=input().split()
  x=int(x)
  y=int(y)
  for j in range(1, 20) :
    if d[j][y]==0 :
      d[j][y]=1
    else :
      d[j][y]=0

    if d[x][j]==0 :
      d[x][j]=1
    else :
      d[x][j]=0

for i in range(1, 20) :
  for j in range(1, 20) :
    print(d[i][j], end=' ')
  print()

h, w = map(int, input().split())
m = [] 

for i in range(h+1) : 
     m.append([]) 
     for j in range(w+1) : 
          m[i].append(0) 

n = int(input()) 

for i in range(n) : 
     l,d,x,y = input().split() 
     if int(d)==0 : 
          for j in range(int(l)) : 
               m[int(x)][int(y)+j] = 1 
     else : 
          for j in range(int(l)) : 
               m[int(x)+j][int(y)] = 1 

for i in range(1, h+1) : 
     for j in range(1, w+1) : 
          print(m[i][j], end=' ') 
     print()

m=[] 

for i in range(12) : 
     m.append([]) 
     for j in range(12) : 
          m[i].append(0) 

for i in range(10) : 
     a=input().split() 
     for j in range(10) : 
          m[i+1][j+1]=int(a[j]) 

x = 2 
y = 2 

while True : 
     if m[x][y] == 0 : 
          m[x][y] = 9 
     elif m[x][y] == 2 : 
          m[x][y] = 9 
          break 

     if (m[x][y+1]==1 and m[x+1][y]==1) or (x==9 and y==9) : 
          break 

     if m[x][y+1] != 1 : 
          y += 1 
     elif m[x+1][y] != 1 : 
          x += 1 

for i in range(1, 11) : 
     for j in range(1, 11) : 
          print(m[i][j], end=' ') 
     print()