# -*- coding: utf-8 -*-
"""LV2.가장 큰 수

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z0cDAaQvgAdqBnI4rPB0fRRPnxPXhu5b
"""

def solution(numbers):
    numbers = list(map(str, numbers))
    numbers.sort(key=lambda x : x*3, reverse = True)
    return str(int(''.join(numbers)))

print(solution([6, 10, 2]))
print(solution([3, 30, 34, 5, 9]))