# -*- coding: utf-8 -*-
"""LV2_H-index

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LJSo0ynLZUOtkzIk3boTtfeVctxHHtOW
"""

def solution(citations):
    citations.sort()
    for idx , v in enumerate(citations):
        if v >= len(citations) - idx :
            return len(citations) - idx
    return 0

print(solution([3, 0, 6, 1, 5]))