# -*- coding: utf-8 -*-
"""10_점수계산

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qm60F-Ubq7G9DRQGQY4Iu9Vex9xv_-PT
"""

n = int(input())
a = list(map(int, input().split()))
sum = 0
cnt = 0

for i in range(n):
    if a[i]==1:
        cnt=cnt+1
        sum=sum+cnt
    else:
        cnt=0
    
print(sum)

