# -*- coding: utf-8 -*-
"""11_회문 문자열 검사

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WvE5b3bWSFACtazpXwE8-GbkIcg0uBCP
"""

n = int(input())

for i in range(1, n+1):
    a = input()
    a = a.lower()
    if a == a[::-1]:
        print("#%d YES" %i)
    else:
        print("#%d NO" %i)