# -*- coding: utf-8 -*-
"""13_카드역배치

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13mDfTACAyDABxueQyOvMCsIgh1nnXMf0
"""

card = [i for i in range(1, 21)]
li = []
for i in range(10):
    a = list(map(int, input().split()))
    li.append(a)

for i in range(len(li)):
    temp = card[li[i][0] - 1:li[i][1]]
    temp.reverse()
    for j in range(len(temp)):
        card[li[i][0]+j-1] = temp[j]

for i in card:
    print(i, end=' ')

