# -*- coding: utf-8 -*-
"""14_두_리스트_합치기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GbvzUbFQdPTiZEe4lyz46QoZ8tPhHW7p
"""

n = int(input())
n_1 = list(map(int, input().split()))

m = int(input())
m_1 = list(map(int, input().split()))

for i in m_1:
    n_1.append(i)

n_1.sort()

for i in n_1:
    print(i, end=' ')