# -*- coding: utf-8 -*-
"""15_수들의 합

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MH3T0zk8V2ncAXpAillo4NC_2ztccnPQ
"""

n, m = map(int, input().split())
li = list(map(int, input().split()))
cnt = 0

for i in range(n):
    if i == n-1:
        if li[i] == m:
            cnt += 1
    else:
        sum = li[i]
        j = 1
        while sum <= m:
            if sum == m:
                cnt += 1
                break
            if i+j <= n-1:
                sum += li[i+j]
                j += 1
            else:
                break

print(cnt)