# -*- coding: utf-8 -*-
"""16_격자판_최대합

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xx905GP3U4YyMFhQHuRD3gbR1viBjryc
"""

n = int(input())
a = [list(map(int, input().split())) for _ in range(n)]
largest = -99999

for i in range(n):
    sum1 = sum2=0
    for j in range(n):
        sum1 += a[i][j]
        sum2 += a[j][i]
    if sum1 > largest:
        largest = sum1
    if sum2 > largest:
        largest = sum2

sum1 = sum2 = 0

for i in range(n):
    sum1 += a[i][i]
    sum2 += a[i][n-i-1]

if sum1 > largest:
    largest = sum1
if sum2 > largest:
    largest = sum2

print(largest)