# -*- coding: utf-8 -*-
"""17_사과나무(다이아몬드)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13PEQiSeyBjrBJApJVlz52nFQOZaGdiHB
"""

n = int(input())
li = [list(map(int, input().split())) for _ in range(n)]
sum = 0
a = n//2
b = n//2

for i in range(n):
    for j in range(a, b+1):
        sum += li[i][j]
    if i < n//2:
        a -= 1
        b += 1
    else:
        a += 1
        b -= 1

print(sum)