# -*- coding: utf-8 -*-
"""18_곳감(모래시계)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e_W0NwDLG4GPURUwoLzW0OlVVa9qLa5M
"""

n = int(input())
li = [list(map(int, input().split())) for _ in range(n)]

m = int(input())
for i in range(m):
    a, b, c = map(int, input().split())
    if b == 0:
        for _ in range(c):
            li[a-1].append(li[a-1].pop(0))
    else:
        for _ in range(c):
            li[a-1].insert(0, li[a-1].pop())

aa = 0
bb = n-1
sum = 0

for i in range(n):
    for j in range(aa, bb+1):
        sum += li[i][j]
    if i < n//2:
        aa += 1
        bb -= 1
    else:
        aa -= 1
        bb += 1

print(sum)