# -*- coding: utf-8 -*-
"""19_봉우리

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MSFLY2s595xw-w9G3HJy7rcM2jF_5jvT
"""

n = int(input())
li = [list(map(int, input().split())) for _ in range(n)]

li.insert(0, [0]*n)
li.append([0]*n)
for i in li:
    i.insert(0, 0)
    i.append(0)

cnt = 0

for i in range(1, n+1):
    for j in range(1, n+1):
        if li[i][j] > li[i-1][j] and li[i][j] > li[i+1][j] and li[i][j] > li[i][j-1] and li[i][j] > li[i][j+1]:
            cnt += 1
print(cnt)