# -*- coding: utf-8 -*-
"""1_K번째약수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uPU79THIMVwz8gFyh56fUqPd-lY8-W81
"""

a, b = map(int, input().split())

c = []

for i in range(1, a+1):
    if a%i == 0:
        c.append(i)

if len(c) >= b-1:
    print(c[b-1])
else:
    print(-1)