# -*- coding: utf-8 -*-
"""20_스도쿠검사

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v9gWgN9ZKkjUO2X9eo-Mygf6wwThp4FK
"""

import copy

li = [list(map(int, input().split())) for _ in range(9)]
c = [1, 2, 3, 4, 5, 6, 7, 8, 9]
copy_li = copy.deepcopy(li)
flag = True

for i in range(len(copy_li)):
    copy_li[i] = sorted(copy_li[i])

for i in range(9):
    if copy_li[i] != c:
        flag = False
    for j in range(9):
        if copy_li[j][i] != i+1:
            flag = False

for i in range(0, 8, 3):
    for j in range(0, 8, 3):
        a = []
        for k in range(i, i+3):
            for l in range(j, j+3):
                a.append(li[k][l])
        a.sort()
        if a != c:
            flag = False

if flag == True:
    print("YES")
else:
    print("NO")