# -*- coding: utf-8 -*-
"""22_이분검색

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tN9PARjrMblgxge9eauJ5raGhU5RjHuC
"""

n, m = map(int, input().split())

li = list(map(int, input().split()))
li.sort()

a = 0
b = n-1
while a <= b:
    center = (a+b) // 2
    if li[center] == m:
        print(center+1)
        break
    elif li[center] > m:
        b = center - 1
    else:
        a = center + 1