# -*- coding: utf-8 -*-
"""23_랜선자르기(결정알고리즘)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wvu5-MWcOf2NeXnoOgdr97CXhOODUHHc
"""

def Count(mid):
    res = 0
    for x in a:
        res += (x//mid)
    return cnt

k, n = map(int, input().split())
a = []
large_num = 0
cnt = 0

for _ in range(k):
    b = int(input())
    a.append(b)
    large_num = max(large_num, b)

lt = 1
rt = large_num

while lt <= rt:
    mid = (lt+rt)//2
    if Count(mid) >= n:
        cnt = mid
        lt = mid + 1
    else:
        rt = mid - 1

print(cnt)