# -*- coding: utf-8 -*-
"""25_마구간_정하기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17UdrU3cUhBPkLRV55VfOnFYZLzIC6-LH
"""

n, c = map(int, input().split())
li = []
m = -999999

for i in range(n):
    a = int(input())
    li.append(a)

li.sort()

for i in range(n):
    for j in range(i, n):
        for k in range(j, n):
            tmp = min(abs(li[i] - li[j]), abs(li[j] - li[k]), abs(li[i] - li[k]))
            if tmp > m:
                m = tmp
print(m)