# -*- coding: utf-8 -*-
"""26_회의실_배정(그리디)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kfAbJnUz2qiVBH51dPZUKxCukseHw4gd
"""

n=int(input())
li=[]

for i in range(n):
    a, b=map(int, input().split())
    li.append((a, b))

li.sort(key=lambda x : (x[1], x[0]))
et=0
cnt=0

for x, y in li:
    if x>=et:
        et=y
        cnt+=1

print(cnt)