# -*- coding: utf-8 -*-
"""27_씨름 선수(그리디)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VcJuRdZXcXyofXfAZ9MBMiYb7mooYdLp
"""

n = int(input())
li = []

for i in range(n):
    h, w = map(int, input().split())
    li.append((h, w))

li.sort(reverse = True)
cnt = 1
large = li[0][1]

for i in range(1, len(li)):
    if li[i][1] > large:
        large = li[i][1]
        cnt += 1

print(cnt)