# -*- coding: utf-8 -*-
"""증가수열 만들기(그리디)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15D9huw7vg762j-OzmhdSR2s0ETBrOwnv
"""

n = int(input())
a = list(map(int, input().split()))

lt = 0
rt = n-1
last = 0
res = ""
tmp = []

while lt <= rt:
    if a[lt] > last:
        tmp.append((a[lt], 'L'))

    if a[rt] > last:
        tmp.append((a[rt], 'R'))
    tmp.sort()

    if len(tmp)==0:
        break;

    else:
        res = res + tmp[0][1]
        last = tmp[0][0]
        if tmp[0][1] == 'L':
            lt = lt+1
        else:
            rt = rt-1
    tmp.clear()

print(len(res))
print(res)