# -*- coding: utf-8 -*-
"""31_역수열(그리디)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MXjdPkzxF4EIKJU-fD8P2RIGErCFFCpS
"""

n = int(input())
a = list(map(int, input().split()))

seq = [0 for i in range(n)]
for i in range(n):
    for j in range(n):
        if(a[i] == 0 and seq[j] == 0):
            seq[j] = i+1
            break
        elif seq[j] == 0:
            a[i] -= 1

for x in seq:
    print(x, end = ' ')