# -*- coding: utf-8 -*-
"""33_쇠막대기

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GUTW-ZlwhdbTnwyFN19cEUbcGsD2rEfF
"""

a = input()

st = []
cnt = 0
for i in range(len(a)):
    if a[i] == '(':
        st.append(a[i])
    else:
        st.pop()
        if a[i-1] == '(':
            cnt += len(st)
        else:
            cnt += 1

print(cnt)