# -*- coding: utf-8 -*-
"""3_K번째 큰 수.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qjOOdHhkQ2qBooq6R5ZOutFmkOgHU-m_
"""

n, m = map(int, input().split())

a = list(map(int, input().split()))
b = []

for i in range(0, n-2):
    for j in range(i+1, n-1):
        for k in range(j+1, n):
            sum = a[i]+a[j]+a[k]
            b.append(sum)
b = list(set(b))
b.sort(reverse=True)

print(b[m-1])