# -*- coding: utf-8 -*-
"""4_대표값.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kmzm_Q61_o-acQW-YpW9GzmdeXdvHljg
"""

n = int(input())
score = list(map(int, input().split()))
subtract = []
min = 99999999

aver_score = round((sum(score) / n))

for i in score:
    subtract.append(abs(i-aver_score))

for idx, j in enumerate(subtract):
    if j < min:
        min = j
        temp = score[idx]
        ind = idx + 1
    elif j == min:
        if score[idx] > temp:
            temp = score[idx]
            ind = idx + 1

print(aver_score, ind)