# -*- coding: utf-8 -*-
"""6_자릿수의합.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UjJ-ZejQXa0SaWMnyeueIKA6CkLvFO5K
"""

def digit_sum(x):
    sum = 0
    while True:
        if x <= 0:
            break
        sum += x % 10
        x = x // 10
    return sum
            
n = int(input())
a = list(map(int, input().split()))
res=0
max=-99999
for i in a:
    c = digit_sum(i)
    if c > max:
        max = c
        res = i
print(res)