# -*- coding: utf-8 -*-
"""7_소수(에라토스테네스 체).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GP-z5pvRWhRCoKBDy5s7y6NPi_Ai9Dil
"""

n = int(input())
a = [0] * (n+1)
cnt = 0

for i in range(2, n+1):
    if a[i] == 0:
        cnt += 1
    for j in range(i, n+1, i):
        a[j] = 1

print(cnt)