# -*- coding: utf-8 -*-
"""8_뒤집은 소수

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10lSeksFqMZZnIdI_RvxJgHxsvLQIWN76
"""

n = int(input())
a = list(map(int, input().split()))

def reverse(x):
    re_num = x
    b = ""
    while re_num > 0:
        b += str(re_num % 10)
        re_num = re_num // 10
    return int(b)

def isPrime(x):
    flag = True
    if x == 1:
        return
    for i in range(2, x):
        if x % i == 0:
            flag = False
    if flag == True:
        return print(x, end=' ')

for i in a:
    isPrime(reverse(i))

